@startuml
title The player must avoid incoming asteroids while shooting down enemies

actor Player
participant GameMap

Player -> GameMap : Control spaceship using arrow keys
Player -> GameMap : Shoot weapons using spacebar
GameMap -> Player : Avoid incoming asteroids
GameMap -> Player : Shoot down enemies
@enduml
