
@startuml

skinparam linetype polyline
component Asteroid

component Bullet
component Collision
component Common
note left of Common
  Contains common classes
  and interfaces
end note
component Core
note left of Core
  The core of the game
  Contains the main game loop
  and the main game logic
end note
component Enemy
component Player

interface IAsteroidSplitter
interface IBulletCreateService
interface IGamePluginService
interface IEntityProcessingService
interface IPostEntityProcessingService

Core -down- IAsteroidSplitter
Core -down- IBulletCreateService
Core -down- IGamePluginService
Core -down- IEntityProcessingService
Core -right- IPostEntityProcessingService

Asteroid -up-( IAsteroidSplitter
Asteroid -up-( IGamePluginService
Asteroid -up-( IEntityProcessingService

Bullet -up-( IBulletCreateService
Bullet -up-( IGamePluginService
Bullet -up-( IEntityProcessingService

Collision -left-( IPostEntityProcessingService

Enemy -up-( IEntityProcessingService
Enemy -up-( IGamePluginService

Player -up-( IEntityProcessingService
Player -up-( IGamePluginService


Common -.up- Core
Common -.up- Asteroid
Common -.up- Bullet
Common -.up- Collision
Common -.up- Enemy
Common -.up- Player


@enduml